### ISSUE TITLE
Work with library system

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-vscode#17]
This is a feature request.

**Comment by ice1000** [comment]
Proposal: make it work out of the box. Basically, when we open a `.aya` file, we find its location, try to find a `aya.json` file by iterating the parent directory, and load the library. In this way, the user won't have to do any in-vscode configuration

**Comment by ice1000** [comment]
> Is this done?

Maybe?

**Comment by ice1000** [comment]
I'm gonna close this as done
