### ISSUE TITLE
Can't download the VSCode extension build artifacts

### ISSUE THREAD

**Issue by noncom** [aya-prover/aya-vscode#26]
The tutorial here https://www.aya-prover.org/guide/vscode-tutorial.html says to go to the aya-vscode github actions https://github.com/aya-prover/aya-vscode/actions/workflows/vsix.yml and to download the artifact from the latest successful run.

But when I try that the artifacts are already expired, since the last run was 2 months ago.

However, going to https://github.com/aya-prover/aya-vscode/releases/tag/nightly-build shows that there's the latest artifact available, the date of it matches the date of the latest run.

So maybe the docs can be updated to reflect this situation better.

**Comment by ice1000** [comment]
Makes sense!
