### ISSUE TITLE
Lost highlight after `C-C C-l`

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-vscode#3]
It's stuck in this line
https://github.com/aya-prover/aya-vscode/blob/76237d1693847fd15bb77a0f710dea5f64d3b684/src/highlight.ts#L72

**Comment by ice1000** [comment]
I propose a different set of shortcuts, because `C-c` is copy.

**Comment by imkiva** [comment]
Using another theme solved this problem, so it might not be our problem

**Comment by imkiva** [comment]
> I propose a different set of shortcuts, because `C-c` is copy.

Yeah, which key do you prefer?

**Comment by ice1000** [comment]
@imkiva 🤷‍♂️

**Comment by ice1000** [comment]
@imkiva What about C-l C-l? We prefix everything with C-l instead (since C-l doesn't seem to be often used)

**Comment by imkiva** [comment]
> @imkiva What about C-l C-l? We prefix everything with C-l instead (since C-l doesn't seem to be often used)

Good idea

**Comment by imkiva** [comment]
changed to `C-l C-l` in `b2a161ec1f0749151cf2aafe6b727d1ae1d0d52f`
