### ISSUE TITLE
How to add new commands?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-vscode#6]
I wanna implement a command like this:

+ VSCode sends the LSP an instance of some subtype of `org.eclipse.lsp4j.TextDocumentPositionParams` (done in this client -- Idk how to do it, I need help!)
+ LSP finds an instance of `Doc` (which, probably we need to convert to plain text before sending to VSCode, but maybe HTML also works?) and a range (done in the compiler, I know how to do it, I don't need help!)
+ VSCode selects the provided range and show the `Doc` somehow, maybe similar to how [GHC-Simple](https://github.com/dramforever/dram.cf/raw/master/repo/vscode-ghc-simple/range-type.png) shows the type of expressions (done in this client -- Idk how to do it, I need help!)

@imkiva need your help!!

**Comment by imkiva** [comment]
> * VSCode sends the LSP an instance of some subtype of `org.eclipse.lsp4j.TextDocumentPositionParams` (done in this client -- Idk how to do it, I need help!)

The client-side should send a named json request (for example `aya/load` here):
https://github.com/aya-prover/aya-vscode/blob/8d1f833377d9e5ac68e6a870f33b00afc06c0fcb/src/server-daemon.ts#L126-L127

The server side should register a json request handler with the same name in `AyaServer`:

https://github.com/aya-prover/aya-dev/blob/3ee50df7ed6e8774491bb453cc342e9fcad30fe7/lsp/src/main/java/org/aya/lsp/server/AyaServer.java#L22-L26

**Comment by imkiva** [comment]
> * LSP finds an instance of `Doc` (which, probably we need to convert to plain text before sending to VSCode, but maybe HTML also works?) and a range (done in the compiler, I know how to do it, I don't need help!)

Yes. HTML works.

**Comment by imkiva** [comment]
> * VSCode selects the provided range and show the `Doc` somehow, maybe similar to how [GHC-Simple](https://github.com/dramforever/dram.cf/raw/master/repo/vscode-ghc-simple/range-type.png) shows the type of expressions (done in this client -- Idk how to do it, I need help!)

idk either. But I found this SO thread: https://stackoverflow.com/questions/47250698/set-selection-range-in-the-visual-studio-code-document

**Comment by re-xyr** [comment]
> Yes. HTML works.

I thought they were sanitized away?

> maybe similar to how GHC-Simple shows the type of expressions

But ghc-simple gives plaintext code annotations.

**Comment by ice1000** [comment]
> But ghc-simple gives plaintext code annotations.

Why not do better if we can

**Comment by re-xyr** [comment]
I think that kind of annotation (next to code) accepts only plaintext.

**Comment by ice1000** [comment]
> I think that kind of annotation (next to code) accepts only plaintext.

Then we'll just use plaintext backend of `Doc`, I think it'll be fine

**Comment by ice1000** [comment]
OMG turns out we have more problems (now we have a problem factory)

**Comment by ice1000** [comment]
I added `computeNF`, can you add vscode support for it too @imkiva 

Btw, I've realized I cannot obtain the source code range for a `CallTerm`. So sad.

**Comment by ice1000** [comment]
@ice1000 I found an unreliable way to do this

**Comment by imkiva** [comment]
> I added `computeNF`, can you add vscode support for it too @imkiva

now vscode supports computeNF

**Comment by ice1000** [comment]
Ok, closing.
